//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloService.WebClient
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using CServiceStack.ProtoBuf;
    using CServiceStack.ServiceHost;
    using CServiceStack.Baiji.Specific;
    using System.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using CServiceStack.ServiceClient;
    using CServiceStack.Common.Types;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/helloservice/v1")]
    [System.Xml.Serialization.XmlRootAttribute("HelloRequest", Namespace="http://soa.ctrip.com/framework/soa/helloservice/v1", IsNullable=false)]
    [DataContract(Name="HelloRequest", Namespace="http://soa.ctrip.com/framework/soa/helloservice/v1")]
    [ProtoContract()]
    public partial class HelloRequestType : ISpecificRecord
    {
        
        private string nameField;
        
        public static readonly CServiceStack.Baiji.Schema.Schema SCHEMA = CServiceStack.Baiji.Schema.Schema.Parse((("{\"type\":\"record\",\"name\":\"HelloRequestType\",\"namespace\":\"" + typeof(HelloRequestType).Namespace) 
                        + "\",\"doc\":null,\"fields\":[{\"name\":\"Name\",\"type\":[\"string\",\"null\"]}]}"));
        
        [DataMember()]
        [ProtoMember(1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        public virtual CServiceStack.Baiji.Schema.Schema GetSchema()
        {
            return SCHEMA;
        }
        
        public virtual object Get(int fieldPos)
        {
            switch(fieldPos)
            {
                case 0: return this.Name;
                default: throw new CServiceStack.Baiji.Exceptions.BaijiRuntimeException("Bad index " + fieldPos + " in Get()");
            }
        }
        
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch(fieldPos)
            {
                case 0: this.Name = (System.String)fieldValue; break;
                default: throw new CServiceStack.Baiji.Exceptions.BaijiRuntimeException("Bad index " + fieldPos + " in Put()");
            }
        }
        
        public virtual object Get(string fieldName)
        {
            var recordSchema = GetSchema() as CServiceStack.Baiji.Schema.RecordSchema;
            if (recordSchema == null)
            {
                return null;
            }
            CServiceStack.Baiji.Schema.Field field;
            if (!recordSchema.TryGetField(fieldName, out field))
            {
                return null;
            }
            return Get(field.Pos);
        }
        
        public virtual void Put(string fieldName, object fieldValue)
        {
            var recordSchema = GetSchema() as CServiceStack.Baiji.Schema.RecordSchema;
            if (recordSchema == null)
            {
                return ;
            }
            CServiceStack.Baiji.Schema.Field field;
            if (!recordSchema.TryGetField(fieldName, out field))
            {
                return ;
            }
            Put(field.Pos, fieldValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/helloservice/v1")]
    [System.Xml.Serialization.XmlRootAttribute("HelloResponse", Namespace="http://soa.ctrip.com/framework/soa/helloservice/v1", IsNullable=false)]
    [DataContract(Name="HelloResponse", Namespace="http://soa.ctrip.com/framework/soa/helloservice/v1")]
    [ProtoContract()]
    public partial class HelloResponseType : ISpecificRecord, IHasResponseStatus
    {
        
        private string helloResultField;
        
        private ResponseStatusType responseStatusField;
        
        public static readonly CServiceStack.Baiji.Schema.Schema SCHEMA = CServiceStack.Baiji.Schema.Schema.Parse(((("{\"type\":\"record\",\"name\":\"HelloResponseType\",\"namespace\":\"" + typeof(HelloResponseType).Namespace) 
                        + (("\",\"doc\":null,\"fields\":[{\"name\":\"HelloResult\",\"type\":[\"string\",\"null\"]},{\"name\":\"R" +
                            "esponseStatus\",\"type\":{\"type\":\"record\",\"name\":\"ResponseStatusType\",\"namespace\":\"" +
                            "" + typeof(ResponseStatusType).Namespace) 
                        + (("\",\"doc\":null,\"fields\":[{\"name\":\"Timestamp\",\"type\":\"datetime\"},{\"name\":\"Ack\",\"type" +
                            "\":{\"type\":\"enum\",\"name\":\"AckCodeType\",\"namespace\":\"" + typeof(AckCodeType).Namespace) 
                        + (("\",\"doc\":null,\"symbols\":[\"Success\",\"Failure\",\"Warning\",\"PartialFailure\"]}},{\"name\"" +
                            ":\"Errors\",\"type\":[{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ErrorDataType" +
                            "\",\"namespace\":\"" + typeof(ErrorDataType).Namespace) 
                        + (("\",\"doc\":null,\"fields\":[{\"name\":\"Message\",\"type\":[\"string\",\"null\"]},{\"name\":\"Error" +
                            "Code\",\"type\":[\"string\",\"null\"]},{\"name\":\"StackTrace\",\"type\":[\"string\",\"null\"]},{" +
                            "\"name\":\"SeverityCode\",\"type\":{\"type\":\"enum\",\"name\":\"SeverityCodeType\",\"namespace" +
                            "\":\"" + typeof(SeverityCodeType).Namespace) 
                        + (("\",\"doc\":null,\"symbols\":[\"Error\",\"Warning\"]}},{\"name\":\"ErrorFields\",\"type\":[{\"type" +
                            "\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ErrorFieldType\",\"namespace\":\"" + typeof(ErrorFieldType).Namespace) 
                        + ((@""",""doc"":null,""fields"":[{""name"":""FieldName"",""type"":[""string"",""null""]},{""name"":""ErrorCode"",""type"":[""string"",""null""]},{""name"":""Message"",""type"":[""string"",""null""]}]}},""null""]},{""name"":""ErrorClassification"",""type"":{""type"":""enum"",""name"":""ErrorClassificationCodeType"",""namespace"":""" + typeof(ErrorClassificationCodeType).Namespace) 
                        + (@""",""doc"":null,""symbols"":[""ServiceError"",""ValidationError"",""FrameworkError"",""SLAError""]}}]}},""null""]},{""name"":""Build"",""type"":[""string"",""null""]},{""name"":""Version"",""type"":[""string"",""null""]},{""name"":""Extension"",""type"":[{""type"":""array"",""items"":{""type"":""record"",""name"":""ExtensionType"",""namespace"":""" + typeof(ExtensionType).Namespace)))))))) 
                        + "\",\"doc\":null,\"fields\":[{\"name\":\"Id\",\"type\":[\"string\",\"null\"]},{\"name\":\"Version\",\"" +
                            "type\":[\"string\",\"null\"]},{\"name\":\"ContentType\",\"type\":[\"string\",\"null\"]},{\"name\"" +
                            ":\"Value\",\"type\":[\"string\",\"null\"]}]}},\"null\"]}]}}]}"));
        
        [DataMember()]
        [ProtoMember(1)]
        public string HelloResult
        {
            get
            {
                return this.helloResultField;
            }
            set
            {
                this.helloResultField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(2)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        public virtual CServiceStack.Baiji.Schema.Schema GetSchema()
        {
            return SCHEMA;
        }
        
        public virtual object Get(int fieldPos)
        {
            switch(fieldPos)
            {
                case 0: return this.HelloResult;
                case 1: return this.ResponseStatus;
                default: throw new CServiceStack.Baiji.Exceptions.BaijiRuntimeException("Bad index " + fieldPos + " in Get()");
            }
        }
        
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch(fieldPos)
            {
                case 0: this.HelloResult = (System.String)fieldValue; break;
                case 1: this.ResponseStatus = (ResponseStatusType)fieldValue; break;
                default: throw new CServiceStack.Baiji.Exceptions.BaijiRuntimeException("Bad index " + fieldPos + " in Put()");
            }
        }
        
        public virtual object Get(string fieldName)
        {
            var recordSchema = GetSchema() as CServiceStack.Baiji.Schema.RecordSchema;
            if (recordSchema == null)
            {
                return null;
            }
            CServiceStack.Baiji.Schema.Field field;
            if (!recordSchema.TryGetField(fieldName, out field))
            {
                return null;
            }
            return Get(field.Pos);
        }
        
        public virtual void Put(string fieldName, object fieldValue)
        {
            var recordSchema = GetSchema() as CServiceStack.Baiji.Schema.RecordSchema;
            if (recordSchema == null)
            {
                return ;
            }
            CServiceStack.Baiji.Schema.Field field;
            if (!recordSchema.TryGetField(fieldName, out field))
            {
                return ;
            }
            Put(field.Pos, fieldValue);
        }
    }
    
    /// <summary>
    /// Service client auto-generated by SOA tool, DO NOT CHANGE!
    /// 
    /// 
    /// </summary>
    public class HelloServiceClient : ServiceClientBase<HelloServiceClient>
    {
        
        public const string CodeGeneratorVersion = "2.0.9.0";
        
        public const string OriginalServiceName = "HelloService";
        
        public const string OriginalServiceNamespace = "http://soa.ctrip.com/framework/soa/helloservice/v1";
        
        public const string OriginalServiceType = "NonSLB";
        
        private HelloServiceClient(string baseUri) : 
                base(baseUri)
        {
        }
        
        private HelloServiceClient(string serviceName, string serviceNamespace, string subEnv) : 
                base(serviceName, serviceNamespace, subEnv)
        {
        }
        
        public virtual CheckHealthResponseType CheckHealth(CheckHealthRequestType checkHealthIn)
        {
            return base.Invoke<CheckHealthResponseType>("CheckHealth", checkHealthIn);
        }
        
        public virtual Task<CheckHealthResponseType> CreateAsyncTaskOfCheckHealth(CheckHealthRequestType checkHealthIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<CheckHealthRequestType, CheckHealthResponseType>("CheckHealth", checkHealthIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<CheckHealthResponseType> StartIOCPTaskOfCheckHealth(CheckHealthRequestType checkHealthIn)
        {
            return base.StartIOCPTask<CheckHealthResponseType>("CheckHealth", checkHealthIn);
        }
        
        public virtual HelloResponseType Hello(HelloRequestType helloIn)
        {
            return base.Invoke<HelloResponseType>("Hello", helloIn);
        }
        
        public virtual Task<HelloResponseType> CreateAsyncTaskOfHello(HelloRequestType helloIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<HelloRequestType, HelloResponseType>("Hello", helloIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<HelloResponseType> StartIOCPTaskOfHello(HelloRequestType helloIn)
        {
            return base.StartIOCPTask<HelloResponseType>("Hello", helloIn);
        }
    }
}
